language: node_js
node_js:
  - "node"
script:
  - npm run lint
  - npm run test
  - npm run build
cache:
  directories:
  - node_modules
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: dist
  on:
    branch: master
